// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockerWebAPI.Api.Data;

#nullable disable

namespace StockerWebAPI.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330084929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.InventoryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MovementDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedByUserId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId", "ItemId", "MovementDateTime");

                    b.ToTable("inventory_histories", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "ItemCode", "LocationCode")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ShippingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "ShippingDate", "DestinationCode");

                    b.ToTable("shipping_plans", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShippingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShippingPlanId", "ItemCode", "LocationCode")
                        .IsUnique();

                    b.ToTable("shipping_plan_items", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutedByUserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ExecutedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShippingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedByUserId");

                    b.HasIndex("ShippingPlanId");

                    b.HasIndex("WarehouseId", "ExecutedAt");

                    b.ToTable("shipping_results", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode")
                        .IsUnique();

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Users")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.InventoryHistory", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.AppUser", "ExecutedByUser")
                        .WithMany("InventoryHistories")
                        .HasForeignKey("ExecutedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockerWebAPI.Api.Domain.Entities.InventoryItem", "Item")
                        .WithMany("Histories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockerWebAPI.Api.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecutedByUser");

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingPlan", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("ShippingPlans")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingPlanItem", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.ShippingPlan", "ShippingPlan")
                        .WithMany("Items")
                        .HasForeignKey("ShippingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingPlan");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingResult", b =>
                {
                    b.HasOne("StockerWebAPI.Api.Domain.Entities.AppUser", "ExecutedByUser")
                        .WithMany("ShippingResults")
                        .HasForeignKey("ExecutedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockerWebAPI.Api.Domain.Entities.ShippingPlan", "ShippingPlan")
                        .WithMany()
                        .HasForeignKey("ShippingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StockerWebAPI.Api.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("ShippingResults")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecutedByUser");

                    b.Navigation("ShippingPlan");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("InventoryHistories");

                    b.Navigation("ShippingResults");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.ShippingPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StockerWebAPI.Api.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("ShippingPlans");

                    b.Navigation("ShippingResults");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
