@Host = http://localhost:8080
@WarehouseId = 11111111-1111-1111-1111-111111111111

### Login
POST {{Host}}/auth/login
Content-Type: application/json

{
  "userCode": "worker01",
  "password": "Passw0rd!"
}

### Health
GET {{Host}}/health

